# Generated by Django 5.2.7 on 2025-10-15 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_candidateprofilerolerecommendation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidateprofile",
            options={"ordering": ("-created_at",)},
        ),
    ]
