# Generated by Django 5.2.7 on 2025-11-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0006_resume_processing_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateprofile",
            name="candidate_name",
            field=models.CharField(
                blank=True,
                help_text="Full name parsed from the résumé or provided by a recruiter",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="certifications",
            field=models.TextField(
                blank=True, help_text="Certifications extracted from the résumé"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="education",
            field=models.TextField(
                blank=True, help_text="Education history extracted from the résumé"
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="experience",
            field=models.TextField(
                blank=True,
                help_text="Detailed experience content extracted from the résumé",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="most_recent_title",
            field=models.CharField(
                blank=True,
                help_text="Most recent job title extracted from the résumé",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Phone number if provided in the résumé",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="resume_xml",
            field=models.TextField(
                blank=True,
                help_text="Structured XML representation of the candidate résumé",
            ),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Line-separated list of skills extracted from the résumé",
            ),
        ),
    ]
