# Generated by Django 5.2 on 2025-05-10 21:27

import apps.recruiters.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruiterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credits_total",
                    models.IntegerField(
                        default=100,
                        help_text="Total resume processing credits for the recruiter",
                    ),
                ),
                (
                    "credits_available",
                    models.IntegerField(
                        default=100,
                        help_text="Remaining resume processing credits available",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "recruiter"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOpeningProcessingTask",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("original_text", models.TextField()),
                ("processed_xml", models.TextField(blank=True, null=True)),
                ("created_job_opening_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_processing_tasks",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "original_description",
                    models.TextField(
                        blank=True,
                        help_text="The original, unmodified job description as provided by the recruiter",
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100)),
                (
                    "company",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Company offering this position",
                        max_length=255,
                    ),
                ),
                (
                    "job_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level"),
                            ("junior", "Junior"),
                            ("mid", "Mid-Level"),
                            ("senior", "Senior"),
                            ("manager", "Manager"),
                            ("executive", "Executive"),
                        ],
                        help_text="Experience level for the position",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full-time"),
                            ("part_time", "Part-time"),
                            ("contract", "Contract"),
                            ("temporary", "Temporary"),
                            ("internship", "Internship"),
                        ],
                        help_text="Type of employment arrangement",
                        max_length=20,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "benefits",
                    models.TextField(
                        blank=True,
                        help_text="Benefits offered (health insurance, retirement plans, etc.)",
                    ),
                ),
                (
                    "additional_perks",
                    models.TextField(
                        blank=True,
                        help_text="Additional perks (gym membership, food, etc.)",
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(
                        blank=True,
                        help_text="List required skills with experience levels, e.g., 'Python (3+ years) | React (2+ years) | Agile (familiar)'",
                    ),
                ),
                (
                    "required_qualifications",
                    models.TextField(
                        blank=True,
                        help_text="Formal education, certifications, or qualifications required",
                    ),
                ),
                (
                    "experience_required",
                    models.TextField(
                        blank=True,
                        help_text="Years or type of experience required for this position",
                    ),
                ),
                (
                    "soft_skills",
                    models.TextField(
                        blank=True,
                        help_text="Soft skills like communication, leadership, teamwork, etc.",
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True,
                        help_text="Comprehensive list of job responsibilities",
                    ),
                ),
                (
                    "daily_tasks",
                    models.TextField(
                        blank=True,
                        help_text="Typical daily, weekly, or monthly tasks for this role",
                    ),
                ),
                (
                    "performance_expectations",
                    models.TextField(
                        blank=True,
                        help_text="Performance targets, quality standards, or deadlines",
                    ),
                ),
                (
                    "working_hours",
                    models.CharField(
                        blank=True,
                        help_text="Working hours schedule (e.g., '9-5, M-F')",
                        max_length=100,
                    ),
                ),
                (
                    "work_environment",
                    models.CharField(
                        blank=True,
                        help_text="Work environment (office, remote, hybrid, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "reporting_to",
                    models.CharField(
                        blank=True,
                        help_text="Position or title this role reports to",
                        max_length=100,
                    ),
                ),
                (
                    "travel_requirements",
                    models.CharField(
                        blank=True,
                        help_text="Travel expectations (e.g., '25% travel' or 'occasional travel required')",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("draft", "Draft"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        help_text="Current status of the job opening",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate_pool_id",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Candidate pool to match against (0 = global talent pool)",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_openings",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BulkResumeUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default=apps.recruiters.models.default_pool_name,
                        help_text="Name of this resume pool",
                        max_length=255,
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        help_text="ZIP archive containing PDF resumes",
                        upload_to="bulk_resumes/zips/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed", models.BooleanField(default=False)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_profiles", models.PositiveIntegerField(default=0)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_resume_uploads",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Resume Upload",
                "verbose_name_plural": "Bulk Resume Uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="bulk_resumes/items/")),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_files",
                        to="recruiters.bulkresumeupload",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_files",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume File",
                "verbose_name_plural": "Resume Files",
                "ordering": ["-uploaded_at"],
                "unique_together": {("bulk_upload", "original_filename")},
            },
        ),
    ]
