# Generated by Django 5.1.7 on 2025-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobopening",
            name="experience_years",
        ),
        migrations.AddField(
            model_name="jobopening",
            name="additional_perks",
            field=models.TextField(
                blank=True, help_text="Additional perks (gym membership, food, etc.)"
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="benefits",
            field=models.TextField(
                blank=True,
                help_text="Benefits offered (health insurance, retirement plans, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="daily_tasks",
            field=models.TextField(
                blank=True,
                help_text="Typical daily, weekly, or monthly tasks for this role",
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full_time", "Full-time"),
                    ("part_time", "Part-time"),
                    ("contract", "Contract"),
                    ("temporary", "Temporary"),
                    ("internship", "Internship"),
                ],
                help_text="Type of employment arrangement",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="job_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("entry", "Entry Level"),
                    ("junior", "Junior"),
                    ("mid", "Mid-Level"),
                    ("senior", "Senior"),
                    ("manager", "Manager"),
                    ("executive", "Executive"),
                ],
                help_text="Experience level for the position",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="performance_expectations",
            field=models.TextField(
                blank=True,
                help_text="Performance targets, quality standards, or deadlines",
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="reporting_to",
            field=models.CharField(
                blank=True,
                help_text="Position or title this role reports to",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="required_qualifications",
            field=models.TextField(
                blank=True,
                help_text="Formal education, certifications, or qualifications required",
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="responsibilities",
            field=models.TextField(
                blank=True, help_text="Comprehensive list of job responsibilities"
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="soft_skills",
            field=models.TextField(
                blank=True,
                help_text="Soft skills like communication, leadership, teamwork, etc.",
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="travel_requirements",
            field=models.CharField(
                blank=True,
                help_text="Travel expectations (e.g., '25% travel' or 'occasional travel required')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="work_environment",
            field=models.CharField(
                blank=True,
                help_text="Work environment (office, remote, hybrid, etc.)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="jobopening",
            name="working_hours",
            field=models.CharField(
                blank=True,
                help_text="Working hours schedule (e.g., '9-5, M-F')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="jobopening",
            name="company",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Company offering this position",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="jobopening",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="jobopening",
            name="required_skills",
            field=models.TextField(
                blank=True,
                help_text="List required skills with experience levels, e.g., 'Python (3+ years), React (2+ years), Agile (familiar)'",
            ),
        ),
    ]
