# Generated by Django 5.1.6 on 2025-03-05 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="company_description",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="company_website",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="industry",
        ),
    ]
