# Generated by Django 5.2 on 2025-04-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="subscription_tier",
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="credits_available",
            field=models.IntegerField(
                default=100, help_text="Remaining resume processing credits available"
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="credits_total",
            field=models.IntegerField(
                default=100,
                help_text="Total resume processing credits for the recruiter",
            ),
        ),
    ]
