# Generated by Django 5.2 on 2025-04-22 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkResumeUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zip_file",
                    models.FileField(
                        help_text="ZIP archive containing PDF resumes",
                        upload_to="bulk_resumes/zips/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                (
                    "job_opening",
                    models.ForeignKey(
                        help_text="Job opening these resumes are meant for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_resume_uploads",
                        to="recruiters.jobopening",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_resume_uploads",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Resume Upload",
                "verbose_name_plural": "Bulk Resume Uploads",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="bulk_resumes/items/")),
                ("original_filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulk_upload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_files",
                        to="recruiters.bulkresumeupload",
                    ),
                ),
                (
                    "job_opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_files",
                        to="recruiters.jobopening",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_files",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume File",
                "verbose_name_plural": "Resume Files",
                "ordering": ["-uploaded_at"],
                "unique_together": {("bulk_upload", "original_filename")},
            },
        ),
    ]
