# Generated by Django 5.1.7 on 2025-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="original_description",
            field=models.TextField(
                blank=True,
                help_text="The original, unmodified job description as provided by the recruiter",
            ),
        ),
    ]
