# Generated by Django 5.2.1 on 2025-05-11 23:30

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="jobopening",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="jobopening_title_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="jobopening",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["required_skills"],
                name="jobopening_requiredskills_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
