# Generated by Django 5.2.1 on 2025-05-13 05:45

import apps.core.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0002_jobopening_jobopening_title_trgm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkresumeupload",
            name="zip_file",
            field=models.FileField(
                help_text="ZIP archive containing PDF resumes",
                upload_to="bulk_resumes/zips/",
                validators=[
                    apps.core.upload_validators.validate_zip_file_type,
                    apps.core.upload_validators.validate_zip_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="resumefile",
            name="file",
            field=models.FileField(
                upload_to="bulk_resumes/items/",
                validators=[
                    apps.core.upload_validators.validate_file_extension,
                    apps.core.upload_validators.validate_file_mime,
                    apps.core.upload_validators.validate_file_size,
                ],
            ),
        ),
    ]
