# Generated by Django 5.2 on 2025-04-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0002_remove_recruiterprofile_subscription_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkresumeupload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
