# Generated by Django 5.2 on 2025-04-23 04:53

import apps.recruiters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0002_bulkresumeupload_resumefile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkresumeupload",
            name="job_opening",
        ),
        migrations.RemoveField(
            model_name="resumefile",
            name="job_opening",
        ),
        migrations.AddField(
            model_name="bulkresumeupload",
            name="name",
            field=models.CharField(
                default=apps.recruiters.models.default_pool_name,
                help_text="Name of this resume pool",
                max_length=255,
            ),
        ),
    ]
