# Generated by Django 5.1.7 on 2025-03-23 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0002_remove_jobopening_experience_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterprofile",
            name="subscription_tier",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium")],
                default="free",
                max_length=20,
            ),
        ),
    ]
