# Generated by Django 5.2.1 on 2025-05-18 02:43

import apps.core.upload_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0003_alter_bulkresumeupload_zip_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkresumeupload",
            name="zip_file",
            field=models.FileField(
                help_text="ZIP archive containing resumes (PDF, DOCX, etc.)",
                upload_to="bulk_resumes/zips/",
                validators=[
                    apps.core.upload_validators.validate_zip_file_type,
                    apps.core.upload_validators.validate_zip_size,
                ],
            ),
        ),
    ]
