# Generated by Django 5.1.7 on 2025-03-23 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0003_update_subscription_tiers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="is_subscribed",
        ),
    ]
