# Generated by Django 5.2 on 2025-05-01 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0003_bulkresumeupload_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bulkresumeupload",
            old_name="processed_files",
            new_name="processed_profiles",
        ),
    ]
