# Generated by Django 5.2 on 2025-05-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recruiters",
            "0004_rename_processed_files_bulkresumeupload_processed_profiles",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="candidate_pool_id",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Candidate pool to match against (0 = global talent pool)",
            ),
        ),
    ]
