# Generated by Django 5.1.7 on 2025-03-23 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0004_remove_is_subscribed"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobOpeningProcessingTask",
            fields=[
                (
                    "task_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("job_title", models.CharField(max_length=255)),
                ("original_text", models.TextField()),
                ("processed_xml", models.TextField(blank=True, null=True)),
                ("created_job_opening_id", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                ("current_step", models.CharField(blank=True, max_length=100)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_processing_tasks",
                        to="recruiters.recruiterprofile",
                    ),
                ),
            ],
        ),
    ]
