# Generated by Django 5.2.1 on 2025-05-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0005_convert_skill_delimiter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobopening",
            name="required_skills",
            field=models.TextField(
                blank=True,
                help_text="List required skills with experience levels, one per line",
            ),
        ),
    ]
