# Generated by Django 5.1.7 on 2025-03-25 04:45

from django.db import migrations


def update_skills_separator(apps, schema_editor):
    """
    Update the skills separator from comma to pipe.

    This ensures skills like "Data Analytics (Spark, Pandas)" don't get split incorrectly.
    """
    JobOpening = apps.get_model("recruiters", "JobOpening")

    # Get all job openings with required skills
    job_openings = JobOpening.objects.exclude(required_skills="").exclude(
        required_skills__isnull=True
    )

    for job in job_openings:
        # Only if current format is using commas
        if " | " not in job.required_skills and "," in job.required_skills:
            # Split by comma and join with pipe
            skills = [
                skill.strip()
                for skill in job.required_skills.split(",")
                if skill.strip()
            ]
            job.required_skills = " | ".join(skills)
            job.save(update_fields=["required_skills"])


def reverse_skills_separator(apps, schema_editor):
    """
    Revert back to comma separator if needed.
    """
    JobOpening = apps.get_model("recruiters", "JobOpening")

    # Get all job openings with required skills
    job_openings = JobOpening.objects.exclude(required_skills="").exclude(
        required_skills__isnull=True
    )

    for job in job_openings:
        # Only if current format is using pipes
        if " | " in job.required_skills:
            # Split by pipe and join with comma
            skills = [
                skill.strip()
                for skill in job.required_skills.split(" | ")
                if skill.strip()
            ]
            job.required_skills = ", ".join(skills)
            job.save(update_fields=["required_skills"])


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0005_add_job_opening_processing_task"),
    ]

    operations = [
        migrations.RunPython(
            update_skills_separator,
            reverse_skills_separator,
        ),
    ]
