# Generated by Django 5.1.7 on 2025-03-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0006_update_skill_separator"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("closed", "Closed"),
                ],
                default="active",
                help_text="Current status of the job opening",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobopening",
            name="required_skills",
            field=models.TextField(
                blank=True,
                help_text="List required skills with experience levels, e.g., 'Python (3+ years) | React (2+ years) | Agile (familiar)'",
            ),
        ),
    ]
