# Generated by Django 5.2.1 on 2025-05-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0006_alter_jobopening_required_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruiterprofile",
            name="total_bulk_uploads_performed",
            field=models.PositiveIntegerField(
                default=0, help_text="Total bulk resume uploads performed"
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="total_candidates_shortlisted",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total candidates shortlisted (decremented when un-shortlisted)",
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="total_resumes_processed",
            field=models.PositiveIntegerField(
                default=0, help_text="Total resumes ever processed"
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="total_shortlist_csvs_generated",
            field=models.PositiveIntegerField(
                default=0, help_text="Total shortlist CSVs generated"
            ),
        ),
        migrations.AddField(
            model_name="recruiterprofile",
            name="total_shortlist_pdfs_generated",
            field=models.PositiveIntegerField(
                default=0, help_text="Total shortlist PDFs generated"
            ),
        ),
    ]
