# Generated by Django 5.2.2 on 2025-06-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0007_recruiterprofile_total_bulk_uploads_performed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruiterprofile",
            name="total_candidates_shortlisted",
            field=models.PositiveIntegerField(
                default=0, help_text="Total candidates shortlisted"
            ),
        ),
    ]
