# Generated by Django 5.1.7 on 2025-03-25 04:57

from django.db import migrations


def populate_job_status(apps, schema_editor):
    """
    Populate the new status field based on existing is_active values.

    For existing records:
    - If is_active=True, set status='active'
    - If is_active=False, set status='closed' (a reasonable default)
    """
    JobOpening = apps.get_model("recruiters", "JobOpening")

    # Update active jobs
    JobOpening.objects.filter(is_active=True).update(status="active")

    # Update inactive jobs (default to closed)
    JobOpening.objects.filter(is_active=False).update(status="closed")


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0007_add_job_status"),
    ]

    operations = [
        migrations.RunPython(
            populate_job_status,
            migrations.RunPython.noop,  # No reverse migration needed
        ),
    ]
