# Generated by Django 5.1.7 on 2025-03-25 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0008_populate_job_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobopening",
            name="is_active",
        ),
    ]
