# Generated by Django 5.2.7 on 2025-10-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0009_recruiterprofile_message_and_interest_counters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="total_interest_requests_sent",
        ),
        migrations.RemoveField(
            model_name="recruiterprofile",
            name="total_messages_sent",
        ),
    ]
