# Generated by Django 5.1.7 on 2025-03-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0009_remove_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="experience_required",
            field=models.TextField(
                blank=True,
                help_text="Years or type of experience required for this position",
            ),
        ),
    ]
