# Generated by Django 5.2.7 on 2025-11-03 05:57

import apps.core.upload_validators
import apps.recruiters.models.bulk_resume_upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recruiters",
            "0010_remove_recruiterprofile_total_interest_requests_sent_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bulkresumeupload",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Bulk Résumé Upload",
                "verbose_name_plural": "Bulk Résumé Uploads",
            },
        ),
        migrations.AlterModelOptions(
            name="resumefile",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "Résumé File",
                "verbose_name_plural": "Résumé Files",
            },
        ),
        migrations.AlterField(
            model_name="bulkresumeupload",
            name="name",
            field=models.CharField(
                default=apps.recruiters.models.bulk_resume_upload.default_pool_name,
                help_text="Name of this résumé pool",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="bulkresumeupload",
            name="zip_file",
            field=models.FileField(
                help_text="ZIP archive containing résumés (PDF, DOCX, etc.)",
                upload_to="bulk_resumes/zips/",
                validators=[
                    apps.core.upload_validators.validate_zip_file_type,
                    apps.core.upload_validators.validate_zip_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="credits_available",
            field=models.IntegerField(
                default=100, help_text="Remaining résumé processing credits available"
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="credits_total",
            field=models.IntegerField(
                default=100,
                help_text="Total résumé processing credits for the recruiter",
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="total_bulk_uploads_performed",
            field=models.PositiveIntegerField(
                default=0, help_text="Total bulk résumé uploads performed"
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="total_resumes_processed",
            field=models.PositiveIntegerField(
                default=0, help_text="Total résumés ever processed"
            ),
        ),
    ]
