# Generated by Django 5.1.7 on 2025-03-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0010_jobopening_experience_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobopening",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("closed", "Closed"),
                ],
                default="draft",
                help_text="Current status of the job opening",
                max_length=20,
            ),
        ),
    ]
