[mypy]
plugins = 
    mypy_django_plugin.main

# Enable type checking of untyped functions
disallow_untyped_defs = false
disallow_incomplete_defs = false

# Disable warnings for missing return types
warn_no_return = false

# Other global settings
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true

# Django settings
[mypy.plugins.django-stubs]
django_settings_module = "hiredar.settings"

# Specify modules that should be ignored
[mypy-django.*]
ignore_missing_imports = True 