# Generated by Django 5.1.7 on 2025-04-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        ("recruiters", "0002_add_original_job_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="job_opening",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="recruiters.jobopening",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="status",
            field=models.CharField(
                choices=[
                    ("interest_requested", "Interest Requested"),
                    ("candidate_interested", "Candidate Interested"),
                    ("candidate_not_interested", "Candidate Not Interested"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="interest_requested",
                max_length=30,
            ),
        ),
    ]
