# Generated by Django 5.1.6 on 2025-03-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobopening",
            name="company",
            field=models.CharField(
                default="", help_text="Company offering this position", max_length=255
            ),
        ),
    ]
