# Generated by Django 5.1.7 on 2025-03-17 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_remove_role_recommendation"),
        ("recruiters", "0002_jobopening"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatematch",
            name="job_opening",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidate_matches",
                to="recruiters.jobopening",
            ),
        ),
        migrations.DeleteModel(
            name="JobOpening",
        ),
    ]
