# Generated by Django 5.2.7 on 2025-11-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_drop_messaging_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageViewCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512, unique=True)),
                ("view_count", models.PositiveBigIntegerField(default=0)),
                ("first_viewed_at", models.DateTimeField(auto_now_add=True)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page view count",
                "verbose_name_plural": "Page view counts",
                "ordering": ["-view_count", "path"],
            },
        ),
    ]
