# Generated by Django 5.2 on 2025-05-10 21:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job_seekers", "0001_initial"),
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "holistic_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0"),
                        help_text="Holistic similarity score (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "skills_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0"),
                        help_text="Skills similarity score (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "experience_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0"),
                        help_text="Experience similarity score (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "wildcard_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0"),
                        help_text="Wildcard similarity score (0-1)",
                        max_digits=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("identified", "Identified"),
                            ("open", "Open"),
                            ("contacted", "Contacted"),
                            ("candidate_interested", "Candidate Interested"),
                            ("candidate_declined", "Candidate Declined"),
                            ("recruiter_rejected", "Recruiter Rejected"),
                        ],
                        default="identified",
                        max_length=20,
                    ),
                ),
                (
                    "is_analyzed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this match has been analyzed by AI",
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("holistic", "Holistic Match"),
                            ("skills", "Skills Match"),
                            ("experience", "Experience Match"),
                            ("wildcard", "Wildcard Match"),
                        ],
                        default="holistic",
                        max_length=20,
                    ),
                ),
                (
                    "match_summary",
                    models.CharField(
                        blank=True,
                        help_text="A headline summarizing why this is a good match",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "match_analysis",
                    models.TextField(
                        blank=True,
                        help_text="Detailed analysis of why this job and candidate match",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_matches",
                        to="recruiters.jobopening",
                    ),
                ),
                (
                    "talent_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_matches",
                        to="job_seekers.talentsheet",
                    ),
                ),
            ],
            options={
                "unique_together": {("job_opening", "talent_sheet", "match_type")},
            },
        ),
    ]
