# Generated by Django 5.1.7 on 2025-03-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0007_copy_location_data"),
        ("matching", "0001_initial"),
        ("recruiters", "0011_alter_jobopening_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatematch",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("top", "Top Match"),
                    ("skills", "Skills Match"),
                    ("experience", "Experience Match"),
                    ("wildcard", "Wildcard Match"),
                ],
                default="top",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidatematch",
            unique_together={("job_opening", "job_seeker", "match_type")},
        ),
    ]
