# Generated by Django 5.2.1 on 2025-05-14 02:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatematch",
            name="qualifications_score",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0"),
                help_text="Qualifications similarity score (0-1)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="candidatematch",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("holistic", "Holistic Match"),
                    ("skills", "Skills Match"),
                    ("experience", "Experience Match"),
                    ("wildcard", "Wildcard Match"),
                    ("qualifications", "Qualifications Match"),
                ],
                default="holistic",
                max_length=20,
            ),
        ),
    ]
