# Generated by Django 5.1.7 on 2025-04-07 04:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidatematch",
            name="experience_match_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Experience match score between 0 and 100",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="skills_match_score",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.0"),
                help_text="Skills match score between 0 and 100",
                max_digits=5,
            ),
        ),
    ]
