# Generated by Django 5.1.7 on 2025-04-08 03:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_candidatematch_experience_match_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatematch",
            name="experience_match_score",
        ),
        migrations.RemoveField(
            model_name="candidatematch",
            name="match_score",
        ),
        migrations.RemoveField(
            model_name="candidatematch",
            name="skills_match_score",
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="experience_score",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0"),
                help_text="Experience similarity score (0-1)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="holistic_score",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0"),
                help_text="Holistic similarity score (0-1)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="skills_score",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0"),
                help_text="Skills similarity score (0-1)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="wildcard_score",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0"),
                help_text="Wildcard similarity score (0-1)",
                max_digits=5,
            ),
        ),
    ]
