# Generated by Django 5.1.7 on 2025-03-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0002_add_match_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatematch",
            name="match_type",
            field=models.CharField(
                choices=[
                    ("holistic", "Holistic Match"),
                    ("skills", "Skills Match"),
                    ("experience", "Experience Match"),
                    ("wildcard", "Wildcard Match"),
                ],
                default="holistic",
                max_length=20,
            ),
        ),
    ]
