"""
Migration to remove the `match_type` field from CandidateMatch and update the
unique constraint to be on (`job_opening`, `talent_sheet`) only.

Auto-generated by the AI assistant – run `python manage.py makemigrations`
followed by `python manage.py migrate` to apply.
"""

# Standard library

# Third-party
from decimal import Decimal

from django.db import migrations, models


def consolidate_duplicates(apps, schema_editor):
    """Merge multiple CandidateMatch rows for the same (job, talent) pair.

    Before we can enforce the new unique constraint dropping *match_type*, ensure
    there is at most one row per (job_opening, talent_sheet).
    For each lens score we keep the *maximum* value found among the duplicates.
    The first row in each group is kept and updated; the rest are deleted.
    """

    CandidateMatch = apps.get_model("matching", "CandidateMatch")

    # Identify (job, talent) pairs that have more than one record.
    duplicates = (
        CandidateMatch.objects.values("job_opening_id", "talent_sheet_id")
        .annotate(row_count=models.Count("id"))
        .filter(row_count__gt=1)
    )

    for dup in duplicates:
        job_opening_id = dup["job_opening_id"]
        talent_sheet_id = dup["talent_sheet_id"]

        rows = list(
            CandidateMatch.objects.filter(
                job_opening_id=job_opening_id, talent_sheet_id=talent_sheet_id
            )
        )

        if not rows:
            continue  # Safety guard

        # Choose the first row as the canonical record.
        primary = rows[0]

        # Compute max for each lens.
        primary.holistic_score = max(
            (row.holistic_score for row in rows), default=Decimal("0.0")
        )
        primary.skills_score = max(
            (row.skills_score for row in rows), default=Decimal("0.0")
        )
        primary.experience_score = max(
            (row.experience_score for row in rows), default=Decimal("0.0")
        )
        primary.wildcard_score = max(
            (row.wildcard_score for row in rows), default=Decimal("0.0")
        )
        primary.qualifications_score = max(
            (row.qualifications_score for row in rows), default=Decimal("0.0")
        )

        # Preserve analyzed state and status if any row has it.
        if any(row.is_analyzed for row in rows):
            primary.is_analyzed = True

        # Save consolidated record.
        primary.save(
            update_fields=[
                "holistic_score",
                "skills_score",
                "experience_score",
                "wildcard_score",
                "qualifications_score",
                "is_analyzed",
            ]
        )

        # Delete the remaining duplicates.
        for row in rows[1:]:
            row.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0002_candidatematch_qualifications_score_and_more"),
    ]

    operations = [
        migrations.RunPython(consolidate_duplicates, migrations.RunPython.noop),
        # After consolidating duplicates, update the unique_together so that it no longer references
        migrations.AlterUniqueTogether(
            name="candidatematch",
            unique_together={("job_opening", "talent_sheet")},
        ),
        # Now drop the `match_type` field.
        migrations.RemoveField(
            model_name="candidatematch",
            name="match_type",
        ),
    ]
