# Generated by Django 5.2.1 on 2025-05-19 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0003_remove_match_type"),
        ("recruiters", "0006_alter_jobopening_required_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortlistedMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortlists",
                        to="matching.candidatematch",
                    ),
                ),
                (
                    "job_opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shortlisted_matches",
                        to="recruiters.jobopening",
                    ),
                ),
            ],
            options={
                "unique_together": {("job_opening", "candidate_match")},
            },
        ),
    ]
