# Generated by Django 5.1.7 on 2025-03-27 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0007_copy_location_data"),
        ("matching", "0003_rename_top_to_holistic"),
        ("recruiters", "0011_alter_jobopening_status"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="candidatematch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="is_analyzed",
            field=models.BooleanField(
                default=False, help_text="Whether this match has been analyzed by AI"
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="match_analysis",
            field=models.TextField(
                blank=True,
                help_text="Detailed analysis of why this job and candidate match",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="match_summary",
            field=models.CharField(
                blank=True,
                help_text="A headline summarizing why this is a good match",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="candidatematch",
            name="talent_sheet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_matches",
                to="job_seekers.talentsheet",
            ),
        ),
        migrations.AlterField(
            model_name="candidatematch",
            name="status",
            field=models.CharField(
                choices=[
                    ("identified", "Identified"),
                    ("open", "Open"),
                    ("contacted", "Contacted"),
                    ("candidate_interested", "Candidate Interested"),
                    ("candidate_declined", "Candidate Declined"),
                    ("recruiter_rejected", "Recruiter Rejected"),
                ],
                default="identified",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="candidatematch",
            unique_together={
                ("job_opening", "job_seeker", "talent_sheet", "match_type")
            },
        ),
    ]
