# Generated by Django 5.1.7 on 2025-03-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0006_finalize_candidatematch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidatematch",
            name="is_shortlisted",
        ),
    ]
