# Generated by Django 5.2 on 2025-04-26 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job_seekers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the resume processing completed",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        default="success",
                        help_text="Result of the processing job",
                        max_length=20,
                    ),
                ),
                (
                    "job_seeker_profile",
                    models.ForeignKey(
                        help_text="Job seeker profile that was processed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the resume processing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_processing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Processing Job",
                "verbose_name_plural": "Resume Processing Jobs",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeProcessingTaskProgress",
            fields=[
                (
                    "task_id",
                    models.CharField(
                        help_text="Django Q2 task ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        default="resume_processing",
                        help_text="Type of task being processed",
                        max_length=50,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        default="initializing",
                        help_text="Current step being processed",
                        max_length=100,
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(
                        default=0, help_text="Overall progress percentage (0-100)"
                    ),
                ),
                (
                    "steps_completed",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON list of completed steps",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Status message or error details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_processing_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
