"""
Django settings for hiredar project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse
from uuid import uuid4

from django.contrib.messages import constants as messages
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-s%4$@=b$!wh_0r8w-l^l0l)qippjy4y=kja%y-2033#l%_r%yx"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
]

# Trust the X-Forwarded-Proto header from the load balancer so Django knows it's HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Allow CSRF for our custom domain(s)
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if host not in ("localhost", "127.0.0.1")
]

#
# Storage configuration
#

# 1) Tell Django what the "default" file-storage backend is
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

# 2) Cloudflare-R2 / S3 options
AWS_S3_ENDPOINT_URL = os.getenv("SEVALLA_S3_ENDPOINT")
AWS_ACCESS_KEY_ID = os.getenv("SEVALLA_S3_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("SEVALLA_S3_SECRET")
AWS_STORAGE_BUCKET_NAME = os.getenv("SEVALLA_S3_BUCKET")
AWS_QUERYSTRING_AUTH = False
AWS_S3_REGION_NAME = "auto"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "virtual"
AWS_S3_USE_SSL = True

# 3) Staticfiles / media storages

# Django 5+ uses the STORAGES setting. Configure both the default storage
# (for uploaded media) and the staticfiles storage explicitly so that
# `django.core.files.storage.default_storage` resolves to our S3 backend and
# Whitenoise continues to serve compressed static assets locally.
#
# See: https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-STORAGES
#
# The "default" alias is what `django.core.files.storage.default_storage` picks
# up, while the "staticfiles" alias is used by Django's staticfiles app.
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        # No OPTIONS are required because the S3 credentials are provided via
        # the various AWS_* settings declared above.
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        "OPTIONS": {},
    },
}

# In development we don't want the strict manifest check because it requires
# running `collectstatic` after **every** front-end change. When DEBUG is on,
# fall back to the non-manifest variant so files are served directly.
if DEBUG:
    STORAGES["staticfiles"][
        "BACKEND"
    ] = "whitenoise.storage.CompressedStaticFilesStorage"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Add MIME type for WebP images if you use them
WHITENOISE_MIMETYPES = {
    ".webp": "image/webp",
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for django-allauth
    "django.contrib.postgres",  # Enable Postgres-specific features (trigram indexes)
    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.openid_connect",
    "django_htmx",
    "django_celery_results",
    "storages",  # django-storages for S3 support
    # Project apps
    "apps.authentication.apps.AuthenticationConfig",
    "apps.job_seekers.apps.JobSeekersConfig",
    "apps.recruiters.apps.RecruitersConfig",
    "apps.matching.apps.MatchingConfig",
    "apps.messaging.apps.MessagingConfig",
    "apps.core.apps.CoreConfig",
    "apps.reports.apps.ReportsConfig",
    # Resume processing subsystem
    "apps.resume_processing.apps.ResumeProcessingConfig",
]

# ---------------------------------------------------------------------------
#  Celery
# ---------------------------------------------------------------------------

# Use an in-memory broker by default so the test-suite runs without external
# services.  Production deployments are expected to override these settings
# (e.g. ``BROKER_URL=redis://...``) via environment variables.

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "memory://")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")

# Ensure tasks execute locally and synchronously when the broker is the in-
# memory variant.  This keeps behaviour predictable inside unit tests.

CELERY_TASK_ALWAYS_EAGER = CELERY_BROKER_URL == "memory://"
CELERY_TASK_EAGER_PROPAGATES = True

# Enable extended result attributes including task names, args, kwargs, etc.
CELERY_RESULT_EXTENDED = True

# Default queue / priorities.  Additional queues can be declared through
# environment variables or the Django settings override mechanism.

CELERY_TASK_QUEUES = {
    "default": {
        "exchange": "default",
        "routing_key": "default",
    },
    "high": {
        "exchange": "high",
        "routing_key": "high",
    },
}

CELERY_TASK_DEFAULT_QUEUE = "default"

# Celery Beat schedule for periodic tasks
CELERY_BEAT_SCHEDULE = {
    "cleanup-resume-processing-progress": {
        "task": "apps.resume_processing.tasks.cleanup_tasks.cleanup_resume_processing_progress",
        "schedule": 900.0,  # Every 15 minutes (900 seconds)
        "options": {
            "queue": "default",
        },
    },
}

# Enable Django to find tests in the proper directories
# Add the apps directory to the Python path
# This helps Django's test discovery find the test modules
apps_path = os.path.join(BASE_DIR, "apps")
if apps_path not in sys.path:
    sys.path.insert(0, apps_path)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "hiredar.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "apps/authentication/templates", BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hiredar.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASE configuration: parse full URL if provided, else discrete vars
db_url = os.getenv("DB_URL") or os.getenv("DATABASE_URL")
if db_url:
    parsed = urlparse(db_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": parsed.hostname,
            "PORT": parsed.port or "",
            "NAME": parsed.path.lstrip("/"),
            "USER": parsed.username,
            "PASSWORD": parsed.password or "",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER") or os.getenv("DB_USERNAME"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
        }
    }

# ---------------------------------------------------------------------------
# Cache configuration
# ---------------------------------------------------------------------------
# We use Django's database-cache backend for general caching purposes.
# The cache table will be created with:
#     python manage.py createcachetable django_cache
# In production you may switch to Redis/Memcached by overriding *CACHES* via
# environment-specific settings.

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",  # table name
        "TIMEOUT": 300,  # default TTL (seconds) – individual calls may vary
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "authentication.User"

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of django-allauth
    "django.contrib.auth.backends.ModelBackend",
    # django-allauth specific authentication methods
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# Message settings
MESSAGE_TAGS = {
    messages.ERROR: "error",
    messages.WARNING: "warning",
    messages.SUCCESS: "success",
    messages.INFO: "info",
}

# Allauth settings
# New consolidated signup fields and login methods (replaces older settings)
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"email"}

# Username-related settings that aren't deprecated
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_USERNAME_BLACKLIST = []

# Email and Social Account Verification Settings
# Require email confirmation for all accounts
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

# Email backend configuration
if DEBUG:
    # During development, output emails to console rather than sending
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_VERIFICATION_OVERRIDE_ADDRESS = "verification@hiredar.com"
    print("DEBUG MODE: Using console email backend and override email address")
else:
    # Use SMTP2GO HTTP API backend in production
    EMAIL_BACKEND = "apps.core.email_backends.SMTP2GOAPIEmailBackend"
    EMAIL_VERIFICATION_OVERRIDE_ADDRESS = None

DEFAULT_FROM_EMAIL = "Hiredar <noreply@hiredar.com>"

# SMTP2GO HTTP API settings
SMTP2GO_API_KEY = os.getenv("SMTP2GO_API_KEY")  # must be set in .env

# Social account email handling follows main setting
SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION

# Make allauth automatically log the user back in as soon as their e-mail gets confirmed
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Have the GET request to /confirm‐email/<key>/ actually do
# the confirmation immediately (instead of showing the "click to confirm" page)
ACCOUNT_CONFIRM_EMAIL_ON_GET = True


# Custom function to generate usernames
# - Uses portion of email before @ symbol
# - Adds a random suffix for uniqueness
def custom_username_from_email(email):
    base = email.split("@")[0]
    random_suffix = uuid4().hex[:8]
    return f"{base}_{random_suffix}"


ACCOUNT_ADAPTER = "apps.authentication.adapters.AccountAdapter"


def get_user_display(user):
    """Return the user's email as the display name."""
    return user.email


ACCOUNT_USER_DISPLAY = get_user_display

# Controls the life time of the session
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
ACCOUNT_SESSION_REMEMBER = True

# Login/Logout URLs
LOGIN_REDIRECT_URL = "/auth/profile/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/auth/login/"

# Social Account Providers Configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
    },
    "openid_connect": {
        "APPS": [
            {
                "provider_id": "linkedin",
                "name": "LinkedIn",
                "client_id": os.environ.get("LINKEDIN_CLIENT_ID", ""),
                "secret": os.environ.get("LINKEDIN_CLIENT_SECRET", ""),
                "settings": {"server_url": "https://www.linkedin.com/oauth"},
            },
        ],
        "SCOPE": ["openid", "profile", "email"],
    },
}

# Common settings for all social account providers
SOCIALACCOUNT_ADAPTER = "apps.authentication.adapters.SocialAccountAdapter"
SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = (
    True  # Let users sign up via social accounts without additional form
)
SOCIALACCOUNT_LOGIN_ON_GET = (
    True  # Skip the "Do you want to sign in with social account XYZ" confirmation page
)
SOCIALACCOUNT_FORMS = {
    "signup": "apps.authentication.forms.SocialAccountSignupForm",
}

# CSRF Settings
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_USE_SESSIONS = False  # Use cookies for better compatibility with HTMX
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access the CSRF cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{name}] {levelname} {process:d} {thread:d} {message}",
            "datefmt": "%H:%M:%S",
            "style": "{",
        },
        # Unified simple formatter: timestamp, module name, level, message
        "simple": {
            "format": "{asctime} [{module}] {levelname} {message}",
            "datefmt": "%H:%M:%S",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "hiredar.log"),
            "formatter": "simple",
        },
        "console_simple": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "apps.job_seekers": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "apps.authentication": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "apps.job_seekers.services.recommendation.llm_processor": {
            "handlers": ["console_simple"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Ensure the logs directory exists
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

# --- Custom Application Settings ---

# QuickEmailVerification settings
QUICKEMAILVERIFICATION_API_KEY = os.getenv(
    "QUICKEMAILVERIFICATION_API_KEY"
)  # API key for QuickEmailVerification
USE_QUICKEMAILVERIFICATION_SANDBOX = (
    os.getenv("USE_QUICKEMAILVERIFICATION_SANDBOX", "True") == "True"
)  # toggle sandbox mode

# API Keys (Required - must be set in .env or environment)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")

# Check if required API keys are missing
if not OPENAI_API_KEY:
    print("WARNING: OPENAI_API_KEY is not set in the environment.")
if not PINECONE_API_KEY:
    print("WARNING: PINECONE_API_KEY is not set in the environment.")

# AI Model Selection (Configurable via .env, with defaults)
MATCHING_EMBEDDING_MODEL = os.getenv(
    "MATCHING_EMBEDDING_MODEL", "text-embedding-3-large"
)
RECRUITERS_JOB_PROCESSING_MODEL = os.getenv(
    "RECRUITERS_JOB_PROCESSING_MODEL", "gpt-4.1"
)
JOBSEEKERS_RESUME_PROCESSING_MODEL = os.getenv(
    "JOBSEEKERS_RESUME_PROCESSING_MODEL", "gpt-4.1"
)
JOBSEEKERS_ROLE_RECOMMENDATION_MODEL = os.getenv(
    "JOBSEEKERS_ROLE_RECOMMENDATION_MODEL", "gpt-4.1"
)
JOBSEEKERS_TAGLINE_GENERATION_MODEL = os.getenv(
    "JOBSEEKERS_TAGLINE_GENERATION_MODEL", "gpt-4.1-mini"
)
JOBSEEKERS_TALENT_SHEET_MODEL = os.getenv("JOBSEEKERS_TALENT_SHEET_MODEL", "gpt-4.1")
MATCHING_ANALYSIS_MODEL = os.getenv("MATCHING_ANALYSIS_MODEL", "o4-mini")

# AI Model Configuration (Temperature, Tokens, etc.)
RECRUITERS_JOB_PROCESSING_TEMPERATURE = float(
    os.getenv("RECRUITERS_JOB_PROCESSING_TEMPERATURE", "0.1")
)
JOBSEEKERS_RESUME_PROCESSING_TEMPERATURE = float(
    os.getenv("JOBSEEKERS_RESUME_PROCESSING_TEMPERATURE", "0.1")
)
JOBSEEKERS_RECOMMENDATION_TEMPERATURE = float(
    os.getenv("JOBSEEKERS_RECOMMENDATION_TEMPERATURE", "1.0")
)
JOBSEEKERS_TAGLINE_TEMPERATURE = float(
    os.getenv("JOBSEEKERS_TAGLINE_TEMPERATURE", "1.0")
)
JOBSEEKERS_TAGLINE_MAX_TOKENS = int(os.getenv("JOBSEEKERS_TAGLINE_MAX_TOKENS", "50"))
JOBSEEKERS_TALENT_SHEET_TEMPERATURE = float(
    os.getenv("JOBSEEKERS_TALENT_SHEET_TEMPERATURE", "0.7")
)

# Pinecone Configuration (Configurable via .env, with defaults)
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "job-matcher")
PINECONE_DIMENSIONS = int(os.getenv("PINECONE_DIMENSIONS", "3072"))
PINECONE_PROJECT_NAME = os.getenv("PINECONE_PROJECT_NAME", "Hiredar")
PINECONE_INDEX_HOST = os.getenv("PINECONE_INDEX_HOST", None)
# Ensure STATICFILES_STORAGE mirrors the chosen backend (development or production).
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

# Stripe configuration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_PRICE_IDS = {
    100: os.getenv("STRIPE_PRICE_ID_100", "prod_SD8kW8iecpxmGJ"),
    500: os.getenv("STRIPE_PRICE_ID_500", "prod_SD8mpUBQ3863q0"),
    1000: os.getenv("STRIPE_PRICE_ID_1000", "prod_SD8oe2ca7Wd7O1"),
}

# LinkedIn mobile OAuth settings
LI_CLIENT_ID = os.environ.get("LINKEDIN_CLIENT_ID", "")
LI_CLIENT_SECRET = os.environ.get("LINKEDIN_CLIENT_SECRET", "")
# Desktop OAuth redirect URI (existing allauth callback)
LI_DESKTOP_REDIRECT = os.environ.get(
    "LINKEDIN_DESKTOP_REDIRECT",
    "https://hiredar.com/accounts/oidc/linkedin/login/callback/",
)
# Mobile OAuth redirect URI (universal-link stub)
LI_MOBILE_REDIRECT = os.environ.get(
    "LINKEDIN_MOBILE_REDIRECT", "https://hiredar.com/linkedin-mobile/"
)
