"""
Django settings for hiredar project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse
from uuid import uuid4

from django.contrib.messages import constants as messages
from django.core.management.utils import get_random_secret_key
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").strip().lower() in {"1", "true", "yes", "on"}

# Detect if we are running the collectstatic management command (e.g. during
# container image builds). This allows us to generate a temporary SECRET_KEY and
# relax storage requirements so builds do not fail, while keeping production strict.
IS_COLLECTSTATIC = "collectstatic" in sys.argv

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    # In development, tests, or during collectstatic builds, generate a temporary key
    # so the app can start and build steps can proceed.
    if (
        DEBUG
        or "PYTEST_CURRENT_TEST" in os.environ
        or "pytest" in sys.modules
        or IS_COLLECTSTATIC
    ):
        SECRET_KEY = get_random_secret_key()
    else:
        raise RuntimeError(
            "SECRET_KEY is not set. Provide it via environment variables."
        )

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
]

# Include Django's default test host in development and during pytest runs
# so the test-suite can issue requests without triggering DisallowedHost errors.
if (
    DEBUG or "PYTEST_CURRENT_TEST" in os.environ or "pytest" in sys.modules
) and "testserver" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("testserver")

# URL(s) that the lb_health_check middleware will respond to.
ALIVENESS_URL: list[str] = ["/health-check/"]


# Trust the X-Forwarded-Proto header from the load balancer so Django knows it's HTTPS
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Honor X-Forwarded-Host/Port so Django builds correct URLs behind a proxy
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Allow CSRF for our custom domain(s)
CSRF_TRUSTED_ORIGINS = [
    f"https://{host}"
    for host in ALLOWED_HOSTS
    if isinstance(host, str) and host not in ("localhost", "127.0.0.1")
]

#
# Storage configuration
#

## Cloudflare-R2 / S3 options
AWS_S3_ENDPOINT_URL = os.getenv("SEVALLA_S3_ENDPOINT")
AWS_ACCESS_KEY_ID = os.getenv("SEVALLA_S3_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("SEVALLA_S3_SECRET")
AWS_STORAGE_BUCKET_NAME = os.getenv("SEVALLA_S3_BUCKET")
AWS_QUERYSTRING_AUTH = False
AWS_S3_REGION_NAME = "auto"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = "virtual"
AWS_S3_USE_SSL = True

## Staticfiles / media storages

# Determine storage backend based on environment. In tests or local development
# without S3 credentials, use the filesystem. In production, require S3 to be
# configured and fail fast with a clear error if not provided.
RUNNING_TESTS = "PYTEST_CURRENT_TEST" in os.environ or "pytest" in sys.modules
S3_CONFIGURED = bool(
    AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
)

if RUNNING_TESTS or IS_COLLECTSTATIC or (DEBUG and not S3_CONFIGURED):
    DEFAULT_STORAGE_BACKEND = "django.core.files.storage.FileSystemStorage"
elif not S3_CONFIGURED:
    raise RuntimeError(
        "S3 storage configuration is required in production. Set SEVALLA_S3_BUCKET, "
        "SEVALLA_S3_KEY, SEVALLA_S3_SECRET, and SEVALLA_S3_ENDPOINT, or enable DEBUG "
        "for local development."
    )
else:
    DEFAULT_STORAGE_BACKEND = "storages.backends.s3boto3.S3Boto3Storage"

# Django 5+ uses the STORAGES setting. Configure both the default storage
# (for uploaded media) and the staticfiles storage explicitly so that
# `django.core.files.storage.default_storage` resolves to the selected backend and
# Whitenoise continues to serve compressed static assets locally.
#
# See: https://docs.djangoproject.com/en/5.1/ref/settings/#std-setting-STORAGES
#
# The "default" alias is what `django.core.files.storage.default_storage` picks
# up, while the "staticfiles" alias is used by Django's staticfiles app.
STORAGES = {
    "default": {
        "BACKEND": DEFAULT_STORAGE_BACKEND,
        # No OPTIONS are required because the S3 credentials are provided via
        # the various AWS_* settings declared above (when using S3). The file
        # system backend uses MEDIA_ROOT by default and requires no options.
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        "OPTIONS": {},
    },
}

# In development we don't want the strict manifest check because it requires
# running `collectstatic` after **every** front-end change. When DEBUG is on,
# fall back to the non-manifest variant so files are served directly.
if DEBUG:
    STORAGES["staticfiles"][
        "BACKEND"
    ] = "whitenoise.storage.CompressedStaticFilesStorage"

# Keep legacy setting in sync for compatibility
DEFAULT_FILE_STORAGE = STORAGES["default"]["BACKEND"]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Add MIME type for WebP images if you use them
WHITENOISE_MIMETYPES = {
    ".webp": "image/webp",
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for django-allauth
    "django.contrib.postgres",  # Enable Postgres-specific features (trigram indexes)
    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "django_htmx",
    "markdownify",
    "django_celery_results",
    "storages",  # django-storages for S3 support
    # Project apps
    "apps.authentication.apps.AuthenticationConfig",
    "apps.candidates.apps.CandidatesConfig",
    "apps.job_seekers.apps.JobSeekersConfig",
    "apps.recruiters.apps.RecruitersConfig",
    "apps.matching.apps.MatchingConfig",
    "apps.core.apps.CoreConfig",
    "apps.reports.apps.ReportsConfig",
    # Resume processing subsystem
    "apps.resume_processing.apps.ResumeProcessingConfig",
    "post_office",
]

# ---------------------------------------------------------------------------
#  django-markdownify configuration
# ---------------------------------------------------------------------------

# Convert single newlines to HTML <br> tags so resume sections that contain
# line-separated items display line breaks even when there are no blank lines
# between them.  We keep built-in sanitisation via Bleach and extend the
# allowed tag list to include <br> explicitly.

MARKDOWNIFY = {
    "default": {
        "BLEACH": True,
        "STRIP": True,
        # Add <br> so the nl2br extension’s output isn’t stripped.
        "WHITELIST_TAGS": [
            "a",
            "abbr",
            "acronym",
            "b",
            "blockquote",
            "code",
            "em",
            "i",
            "li",
            "ol",
            "strong",
            "ul",
            "p",
            "br",
            "h1",
            "h2",
            "h3",
        ],
        # Use fully-qualified paths so the Python-Markdown loader can find them.
        "MARKDOWN_EXTENSIONS": [
            "markdown.extensions.sane_lists",  # better list handling
        ],
    }
}

# ---------------------------------------------------------------------------
#  Celery
# ---------------------------------------------------------------------------

# Use an in-memory broker by default so the test-suite runs without external
# services.  Production deployments are expected to override these settings
# (e.g. ``BROKER_URL=redis://...``) via environment variables.

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "memory://")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "django-db")

# Ensure tasks execute locally and synchronously when the broker is the in-
# memory variant.  This keeps behavior predictable inside unit tests.

CELERY_TASK_ALWAYS_EAGER = CELERY_BROKER_URL == "memory://"
CELERY_TASK_EAGER_PROPAGATES = True

# Enable extended result attributes including task names, args, kwargs, etc.
CELERY_RESULT_EXTENDED = True

# Worker reliability and fairness under restarts/resource pressure
# - Late ack ensures tasks are re-queued if a worker dies mid-execution
# - Reject on worker lost signals the broker to redeliver in-flight tasks
# - Prefetch multiplier 1 prevents a single worker from hoarding tasks
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Default queue / priorities.  Additional queues can be declared through
# environment variables or the Django settings override mechanism.

CELERY_TASK_QUEUES = {
    "default": {
        "exchange": "default",
        "routing_key": "default",
    },
    "high": {
        "exchange": "high",
        "routing_key": "high",
    },
}

CELERY_TASK_DEFAULT_QUEUE = "default"

# Celery Beat schedule for periodic tasks
CELERY_BEAT_SCHEDULE = {
    "cleanup-resume-processing-progress": {
        "task": "apps.resume_processing.tasks.cleanup_tasks.cleanup_resume_processing_progress",
        "schedule": 900.0,  # Every 15 minutes (900 seconds)
        "options": {
            "queue": "default",
        },
    },
}

# Enable Django to find tests in the proper directories
# Add the apps directory to the Python path
# This helps Django's test discovery find the test modules
apps_path = os.path.join(BASE_DIR, "apps")
if apps_path not in sys.path:
    sys.path.insert(0, apps_path)

MIDDLEWARE = [
    "lb_health_check.middleware.AliveCheck",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.core.middleware.timezone_middleware.UserTimezoneMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "hiredar.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "apps/authentication/templates", BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hiredar.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASE configuration: parse full URL if provided, else discrete vars
db_url = os.getenv("DB_URL") or os.getenv("DATABASE_URL")
if db_url:
    parsed = urlparse(db_url)
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": parsed.hostname,
            "PORT": parsed.port or "",
            "NAME": parsed.path.lstrip("/"),
            "USER": parsed.username,
            "PASSWORD": parsed.password or "",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": os.getenv("DB_HOST"),
            "PORT": os.getenv("DB_PORT"),
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER") or os.getenv("DB_USERNAME"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
        }
    }
    # Fallback to a local SQLite database if no name is configured. This
    # ensures the test-suite runs without requiring external environment
    # variables or PostgreSQL service.
    if not DATABASES["default"]["NAME"]:
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }

# ---------------------------------------------------------------------------
# Cache configuration
# ---------------------------------------------------------------------------
# We use Django's database-cache backend for general caching purposes.
# The cache table will be created with:
#     python manage.py createcachetable django_cache
# In production you may switch to Redis/Memcached by overriding *CACHES* via
# environment-specific settings.

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",  # table name
        "TIMEOUT": 300,  # default TTL (seconds) – individual calls may vary
    }
}

# Use an in-memory cache backend when running tests so the test-suite does not
# require the django_cache table to exist.
if "PYTEST_CURRENT_TEST" in os.environ or "pytest" in sys.modules:
    CACHES["default"] = {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "test-cache",
    }
    # Force Celery to use in-memory broker during tests to avoid external deps
    CELERY_BROKER_URL = "memory://"
    CELERY_RESULT_BACKEND = "cache+memory://"
    CELERY_TASK_ALWAYS_EAGER = True
    CELERY_TASK_EAGER_PROPAGATES = True
    CELERY_TASK_STORE_EAGER_RESULT = True

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "authentication.User"

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of django-allauth
    "django.contrib.auth.backends.ModelBackend",
    # django-allauth specific authentication methods
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# Message settings
MESSAGE_TAGS = {
    messages.ERROR: "error",
    messages.WARNING: "warning",
    messages.SUCCESS: "success",
    messages.INFO: "info",
}

# Allauth settings
# New consolidated signup fields and login methods (replaces older settings)
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"email"}

# Username-related settings that aren't deprecated
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_USERNAME_BLACKLIST = []

# Email and Social Account Verification Settings
# Email confirmation is optional; users can log in without verifying
ACCOUNT_EMAIL_VERIFICATION = "optional"

# ---------------------------------------------------------------------------
#  Email backend configuration (via django-post-office)
# ---------------------------------------------------------------------------

# Resolve the *actual* backend we want Post-Office to delegate to.  During
# development we keep using Django's console backend so e-mails are printed to
# stdout.  In production we continue to use the custom SMTP2GO HTTP backend.
REAL_EMAIL_BACKEND = (
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "apps.core.email_backends.SMTP2GOAPIEmailBackend"
)

# Post-Office integration – queue e-mails to the database and let Celery flush
# them asynchronously.  The ``BACKENDS`` mapping tells Post-Office what engine
# to use when actually sending.
POST_OFFICE = {
    "BACKENDS": {
        "default": REAL_EMAIL_BACKEND,
    },
    # Enable the built-in Celery tasks so ``send_queued_mail`` is dispatched
    # automatically rather than being run by a management command.
    "CELERY_ENABLED": True,
}

# Point Django to Post-Office's email backend so **all** calls to
# ``EmailMessage.send()`` are transparently queued.
EMAIL_BACKEND = "post_office.EmailBackend"

# Email confirmation overriding address remains useful during development.
EMAIL_VERIFICATION_OVERRIDE_ADDRESS = "verification@hiredar.com" if DEBUG else None

# Ensure Celery Beat periodically flushes the queue (every minute).
if "post_office" in INSTALLED_APPS:
    CELERY_BEAT_SCHEDULE.setdefault(
        "send-queued-mail",
        {
            "task": "post_office.tasks.send_queued_mail",
            "schedule": 60.0,  # once per minute
            "options": {"queue": "default"},
        },
    )

# Default from email
DEFAULT_FROM_EMAIL = "Hiredar <noreply@hiredar.com>"

# SMTP2GO HTTP API settings
SMTP2GO_API_KEY = os.getenv("SMTP2GO_API_KEY")  # must be set in .env

# Social account email handling follows main setting
SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION

# Make allauth automatically log the user back in as soon as their e-mail gets confirmed
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Have the GET request to /confirm‐email/<key>/ actually do
# the confirmation immediately (instead of showing the "click to confirm" page)
ACCOUNT_CONFIRM_EMAIL_ON_GET = True


# Custom function to generate usernames
# - Uses portion of email before @ symbol
# - Adds a random suffix for uniqueness
def custom_username_from_email(email):
    """Create a unique username from an e-mail address.

    Uses the local part of the e-mail (before the '@') and appends an
    8-character random hexadecimal suffix to reduce collisions.
    """
    base = email.split("@")[0]
    random_suffix = uuid4().hex[:8]
    return f"{base}_{random_suffix}"


ACCOUNT_ADAPTER = "apps.authentication.adapters.AccountAdapter"


def get_user_display(user):
    """Return the user's email as the display name."""
    return user.email


ACCOUNT_USER_DISPLAY = get_user_display

# Controls the life time of the session
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
ACCOUNT_SESSION_REMEMBER = True

# Login/Logout URLs
LOGIN_REDIRECT_URL = "/auth/profile/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/auth/login/"

# Social Account Providers Configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
    },
}

OPENID_CONNECT_URL_PREFIX = "oidc"

# Common settings for all social account providers
SOCIALACCOUNT_ADAPTER = "apps.authentication.adapters.SocialAccountAdapter"
SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = (
    True  # Let users sign up via social accounts without additional form
)
SOCIALACCOUNT_LOGIN_ON_GET = (
    True  # Skip the "Do you want to sign in with social account XYZ" confirmation page
)
SOCIALACCOUNT_FORMS = {
    "signup": "apps.authentication.forms.SocialAccountSignupForm",
}

# CSRF Settings
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_USE_SESSIONS = False  # Use cookies for better compatibility with HTMX
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access the CSRF cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} [{name}] {levelname} {process:d} {thread:d} {message}",
            "datefmt": "%H:%M:%S",
            "style": "{",
        },
        # Unified simple formatter: timestamp, module name, level, message
        "simple": {
            "format": "{asctime} [{module}] {levelname} {message}",
            "datefmt": "%H:%M:%S",
            "style": "{",
        },
    },
    "filters": {
        "ignore_disallowed_host": {
            "()": "apps.core.logging.IgnoreDisallowedHostFilter",
        }
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["ignore_disallowed_host"],
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "hiredar.log"),
            "formatter": "simple",
            "filters": ["ignore_disallowed_host"],
        },
        "console_simple": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["ignore_disallowed_host"],
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        # Silence noisy DisallowedHost tracebacks while keeping a concise log line
        "django.security.DisallowedHost": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        # Apply the same filtering to request logger in case DisallowedHost bubbles there
        "django.request": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": True,
        },
        "apps.job_seekers": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "apps.authentication": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "apps.matching": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "apps.job_seekers.services.recommendation.llm_processor": {
            "handlers": ["console_simple"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Ensure the logs directory exists
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)

# --- Custom Application Settings ---

# QuickEmailVerification settings
QUICKEMAILVERIFICATION_API_KEY = os.getenv(
    "QUICKEMAILVERIFICATION_API_KEY"
)  # API key for QuickEmailVerification
USE_QUICKEMAILVERIFICATION_SANDBOX = (
    os.getenv("USE_QUICKEMAILVERIFICATION_SANDBOX", "True") == "True"
)  # toggle sandbox mode

# API Keys (Required - must be set in .env or environment)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")

# Check if required API keys are missing
if not OPENAI_API_KEY:
    print("WARNING: OPENAI_API_KEY is not set in the environment.")
if not PINECONE_API_KEY:
    print("WARNING: PINECONE_API_KEY is not set in the environment.")

# AI Model Selection (Configurable via .env, with defaults)
MATCHING_EMBEDDING_MODEL = os.getenv(
    "MATCHING_EMBEDDING_MODEL", "text-embedding-3-large"
)
MATCHING_MIN_SCORE = float(os.getenv("MATCHING_MIN_SCORE", "0.5"))

# Job Opening Processing
RECRUITERS_JOB_PROCESSING_MODEL = os.getenv("RECRUITERS_JOB_PROCESSING_MODEL", "gpt-5")
RECRUITERS_JOB_PROCESSING_REASONING_EFFORT = os.getenv(
    "RECRUITERS_JOB_PROCESSING_REASONING_EFFORT", "minimal"
)

# Resume Processing
JOBSEEKERS_RESUME_PROCESSING_MODEL = os.getenv(
    "JOBSEEKERS_RESUME_PROCESSING_MODEL", "gpt-5"
)
JOBSEEKERS_RESUME_PROCESSING_REASONING_EFFORT = os.getenv(
    "JOBSEEKERS_RESUME_PROCESSING_REASONING_EFFORT", "minimal"
)

# Job Seeker Role Recommendations
JOBSEEKERS_ROLE_RECOMMENDATION_MODEL = os.getenv(
    "JOBSEEKERS_ROLE_RECOMMENDATION_MODEL", "gpt-5"
)
JOBSEEKERS_ROLE_RECOMMENDATION_REASONING_EFFORT = os.getenv(
    "JOBSEEKERS_ROLE_RECOMMENDATION_REASONING_EFFORT", "medium"
)

# Job Seeker Tagline Generation
JOBSEEKERS_TAGLINE_GENERATION_MODEL = os.getenv(
    "JOBSEEKERS_TAGLINE_GENERATION_MODEL", "gpt-5"
)
JOBSEEKERS_TAGLINE_GENERATION_REASONING_EFFORT = os.getenv(
    "JOBSEEKERS_TAGLINE_GENERATION_REASONING_EFFORT", "minimal"
)
JOBSEEKERS_TAGLINE_MAX_ATTEMPTS = int(os.getenv("JOBSEEKERS_TAGLINE_MAX_ATTEMPTS", "3"))

# Job Seeker Talent Sheet Generation
JOBSEEKERS_TALENT_SHEET_MODEL = os.getenv("JOBSEEKERS_TALENT_SHEET_MODEL", "gpt-5")
JOBSEEKERS_TALENT_SHEET_REASONING_EFFORT = os.getenv(
    "JOBSEEKERS_TALENT_SHEET_REASONING_EFFORT", "low"
)

# Matching Analysis
MATCHING_ANALYSIS_MODEL = os.getenv("MATCHING_ANALYSIS_MODEL", "gpt-5")
MATCHING_ANALYSIS_REASONING_EFFORT = os.getenv(
    "MATCHING_ANALYSIS_REASONING_EFFORT", "medium"
)

# AI Model Configuration (Tokens)
JOBSEEKERS_TAGLINE_MAX_TOKENS = int(os.getenv("JOBSEEKERS_TAGLINE_MAX_TOKENS", "50"))

# Pinecone Configuration (Configurable via .env, with defaults)
PINECONE_INDEX_NAME = os.getenv("PINECONE_INDEX_NAME", "job-matcher")
PINECONE_DIMENSIONS = int(os.getenv("PINECONE_DIMENSIONS", "3072"))
PINECONE_PROJECT_NAME = os.getenv("PINECONE_PROJECT_NAME", "Hiredar")
PINECONE_INDEX_HOST = os.getenv("PINECONE_INDEX_HOST", None)
# Ensure STATICFILES_STORAGE mirrors the chosen backend (development or production).
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]

# Stripe configuration
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY")
STRIPE_PRICE_IDS = {
    100: os.getenv("STRIPE_PRICE_ID_100", "prod_SD8kW8iecpxmGJ"),
    500: os.getenv("STRIPE_PRICE_ID_500", "prod_SD8mpUBQ3863q0"),
    1000: os.getenv("STRIPE_PRICE_ID_1000", "prod_SD8oe2ca7Wd7O1"),
}
