"""
Django settings for hiredar project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path
from uuid import uuid4

from django.contrib.messages import constants as messages
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-s%4$@=b$!wh_0r8w-l^l0l)qippjy4y=kja%y-2033#l%_r%yx"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True") == "True"

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # Required for django-allauth
    # Third-party apps
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.linkedin_oauth2",
    "django_htmx",
    "django_q",  # Django Q2 for background tasks
    # Project apps
    "apps.authentication.apps.AuthenticationConfig",
    "apps.job_seekers.apps.JobSeekersConfig",
    "apps.recruiters.apps.RecruitersConfig",
    "apps.matching.apps.MatchingConfig",
    "apps.messaging.apps.MessagingConfig",
    "apps.core.apps.CoreConfig",
]

# Enable Django to find tests in the proper directories
# Add the apps directory to the Python path
# This helps Django's test discovery find the test modules
apps_path = os.path.join(BASE_DIR, "apps")
if apps_path not in sys.path:
    sys.path.insert(0, apps_path)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",  # HTMX middleware
    "allauth.account.middleware.AccountMiddleware",  # Allauth middleware
]

ROOT_URLCONF = "hiredar.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hiredar.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (Uploaded files)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom user model
AUTH_USER_MODEL = "authentication.User"

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of django-allauth
    "django.contrib.auth.backends.ModelBackend",
    # django-allauth specific authentication methods
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# Message settings
MESSAGE_TAGS = {
    messages.ERROR: "error",
    messages.WARNING: "warning",
    messages.SUCCESS: "success",
    messages.INFO: "info",
}

# Allauth settings
# New consolidated signup fields and login methods (replaces older settings)
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"email"}

# Username-related settings that aren't deprecated
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"
ACCOUNT_USERNAME_BLACKLIST = []


# Custom function to generate usernames
# - Uses portion of email before @ symbol
# - Adds a random suffix for uniqueness
def custom_username_from_email(email):
    base = email.split("@")[0]
    random_suffix = uuid4().hex[:8]
    return f"{base}_{random_suffix}"


ACCOUNT_ADAPTER = "apps.authentication.adapters.AccountAdapter"

# Temporarily disable email verification, but keep for future with SendGrid
# Set to "mandatory" when ready to enforce verification
ACCOUNT_EMAIL_VERIFICATION = "none"  # Options: "none", "optional", "mandatory"


def get_user_display(user):
    """Return the user's email as the display name."""
    return user.email


ACCOUNT_USER_DISPLAY = get_user_display

# Controls the life time of the session
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
ACCOUNT_SESSION_REMEMBER = True

# Login/Logout URLs
LOGIN_REDIRECT_URL = "/auth/profile/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "/auth/login/"

# Social Account Providers Configuration
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
            "secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
    },
    "linkedin_oauth2": {
        "APP": {
            "client_id": os.environ.get("LINKEDIN_CLIENT_ID", ""),
            "secret": os.environ.get("LINKEDIN_CLIENT_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["r_liteprofile", "r_emailaddress"],
        "PROFILE_FIELDS": [
            "id",
            "first-name",
            "last-name",
            "email-address",
        ],
    },
}

# Common settings for all social account providers
SOCIALACCOUNT_ADAPTER = "apps.authentication.adapters.SocialAccountAdapter"
SOCIALACCOUNT_EMAIL_VERIFICATION = ACCOUNT_EMAIL_VERIFICATION
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_AUTO_SIGNUP = (
    True  # Let users sign up via social accounts without additional form
)
SOCIALACCOUNT_LOGIN_ON_GET = (
    True  # Skip the "Do you want to sign in with social account XYZ" confirmation page
)
SOCIALACCOUNT_FORMS = {
    "signup": "apps.authentication.forms.SocialAccountSignupForm",
}

# Email backend (for development)
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# CSRF Settings
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_USE_SESSIONS = False  # Use cookies for better compatibility with HTMX
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript to access the CSRF cookie
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS

# Django Q2 configuration
Q_CLUSTER = {
    "name": "hiredar",
    "workers": 4,
    "recycle": 500,
    "timeout": 60,
    "retry": 60,
    "compress": True,
    "save_limit": 250,
    "queue_limit": 500,
    "cpu_affinity": 1,
    "label": "Django Q2",
    "orm": "default",  # Use Django ORM as broker (no Redis needed)
}

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join(BASE_DIR, "logs", "hiredar.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "apps.job_seekers": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# Ensure the logs directory exists
os.makedirs(os.path.join(BASE_DIR, "logs"), exist_ok=True)
