# Generated by Django 5.1.7 on 2025-03-15 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated list of skills"
                    ),
                ),
                ("experience", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "desired_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "current_position",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "professional_summary",
                    models.TextField(
                        blank=True,
                        help_text="Professional summary highlighting experience and qualifications",
                        null=True,
                    ),
                ),
                (
                    "resume_xml",
                    models.TextField(
                        blank=True,
                        help_text="XML representation of the parsed resume",
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "job_seeker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_seeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
