# Generated by Django 5.1.7 on 2025-03-28 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Pipe-separated list of skills"
                    ),
                ),
                ("experience", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "desired_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "most_recent_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "professional_summary",
                    models.TextField(
                        blank=True,
                        help_text="Professional summary highlighting experience and qualifications",
                        null=True,
                    ),
                ),
                (
                    "personal_tagline",
                    models.CharField(
                        blank=True,
                        help_text="AI-generated personal identity tagline",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "resume_xml",
                    models.TextField(
                        blank=True,
                        help_text="XML representation of the parsed resume",
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Job seeker's location", max_length=100
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "job_seeker"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_seeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResumeProcessingTaskProgress",
            fields=[
                (
                    "task_id",
                    models.CharField(
                        help_text="Django Q2 task ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        default="resume_processing",
                        help_text="Type of task being processed",
                        max_length=50,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        default="initializing",
                        help_text="Current step being processed",
                        max_length=100,
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(
                        default=0, help_text="Overall progress percentage (0-100)"
                    ),
                ),
                (
                    "steps_completed",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON list of completed steps",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Status message or error details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_processing_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_title",
                    models.CharField(
                        help_text="The title of the recommended role, in title case (e.g., 'Senior Software Engineer')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A concise description of the role, outlining key responsibilities and value proposition"
                    ),
                ),
                (
                    "is_candidate_interested",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the job seeker has expressed interest in this role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this recommendation was generated",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        help_text="The job seeker this role recommendation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_recommendations",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["role_title"],
            },
        ),
        migrations.CreateModel(
            name="TalentSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotional_blurb",
                    models.TextField(
                        help_text="AI-generated promotional summary highlighting the candidate's unique value proposition"
                    ),
                ),
                (
                    "skill_overview",
                    models.TextField(
                        help_text="Concise overview of the candidate's key skills and competencies"
                    ),
                ),
                (
                    "ideal_roles",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of ideal roles, populated from their interested role recommendations",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary expectation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary expectation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this talent sheet is published and available for matching to job openings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_seeker",
                    models.OneToOneField(
                        help_text="The job seeker this talent sheet is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_sheet",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
            ],
        ),
    ]
