# Generated by Django 5.2 on 2025-04-26 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("recruiters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobSeekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "skills",
                    models.TextField(
                        blank=True, help_text="Pipe-separated list of skills"
                    ),
                ),
                ("experience", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                ("certifications", models.TextField(blank=True, null=True)),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "desired_role",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "most_recent_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "professional_summary",
                    models.TextField(
                        blank=True,
                        help_text="Professional summary highlighting experience and qualifications",
                        null=True,
                    ),
                ),
                (
                    "personal_tagline",
                    models.CharField(
                        blank=True,
                        help_text="AI-generated personal identity tagline",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "resume_xml",
                    models.TextField(
                        blank=True,
                        help_text="XML representation of the parsed resume",
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Job seeker's location", max_length=100
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_title",
                    models.CharField(
                        help_text="The title of the recommended role, in title case (e.g., 'Senior Software Engineer')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A concise description of the role, outlining key responsibilities and value proposition"
                    ),
                ),
                (
                    "is_candidate_interested",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether the job seeker has expressed interest in this role",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this recommendation was generated",
                    ),
                ),
                (
                    "job_seeker",
                    models.ForeignKey(
                        help_text="The job seeker this role recommendation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_recommendations",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TalentSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotional_blurb",
                    models.TextField(
                        help_text="AI-generated promotional summary highlighting the candidate's unique value proposition"
                    ),
                ),
                (
                    "skill_overview",
                    models.TextField(
                        help_text="Concise overview of the candidate's key skills and competencies"
                    ),
                ),
                (
                    "ideal_roles",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of ideal roles, populated from their interested role recommendations",
                    ),
                ),
                (
                    "personal_tagline",
                    models.CharField(
                        blank=True,
                        help_text="AI-generated personal identity tagline",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary expectation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this talent sheet is published and available for matching to job openings",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_seeker",
                    models.OneToOneField(
                        help_text="The job seeker this talent sheet is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_sheet",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UploadedResumePool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Label for this pool (e.g. "March 2024 Upload")',
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_opening",
                    models.ForeignKey(
                        blank=True,
                        help_text="Job opening associated with this pool (optional, non-ownership)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_resume_pools",
                        to="recruiters.jobopening",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "recruiter"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_resume_pools",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
