# Generated by Django 5.2 on 2025-04-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="candidate_name",
            field=models.CharField(
                blank=True,
                help_text="Parsed candidate name from resume for pool-owned profiles",
                max_length=150,
            ),
        ),
    ]
