# Generated by Django 5.1.7 on 2025-03-18 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolerecommendation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name="TalentSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promotional_blurb",
                    models.TextField(
                        help_text="AI-generated promotional summary highlighting the candidate's unique value proposition"
                    ),
                ),
                (
                    "skill_overview",
                    models.TextField(
                        help_text="Concise overview of the candidate's key skills and competencies"
                    ),
                ),
                (
                    "ideal_roles",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of ideal roles, populated from their interested role recommendations",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary expectation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary expectation",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job_seeker",
                    models.OneToOneField(
                        help_text="The job seeker this talent sheet is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_sheet",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
            ],
        ),
    ]
