# Generated by Django 5.2.1 on 2025-05-11 23:30

import django.contrib.postgres.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="jobseekerprofile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["skills"],
                name="jobseekerprofile_skills_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
