# Generated by Django 5.1.7 on 2025-03-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talentsheet",
            name="salary_max",
        ),
    ]
