# Generated by Django 5.1.7 on 2025-04-16 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="user",
        ),
    ]
