# Generated by Django 5.1.7 on 2025-03-15 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobseekerprofile",
            old_name="current_position",
            new_name="most_recent_title",
        ),
    ]
