# Generated by Django 5.1.6 on 2025-03-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="resume_xml",
            field=models.TextField(
                blank=True,
                help_text="XML representation of the parsed resume",
                null=True,
            ),
        ),
    ]
