# Generated by Django 5.1.7 on 2025-03-16 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("confidence_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_seeker_recommendations",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-confidence_score"],
            },
        ),
    ]
