# Generated by Django 5.1.7 on 2025-04-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_remove_jobseekerprofile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rolerecommendation",
            name="uploaded_resume_pool",
        ),
        migrations.RemoveField(
            model_name="talentsheet",
            name="uploaded_resume_pool",
        ),
    ]
