# Generated by Django 5.1.7 on 2025-03-15 22:13

from django.db import migrations


def convert_comma_to_pipe(apps, schema_editor):
    """
    Convert comma-separated skills to pipe-separated format
    for all existing JobSeekerProfile records.
    """
    JobSeekerProfile = apps.get_model("job_seekers", "JobSeekerProfile")

    # Get all profiles with skills
    profiles = JobSeekerProfile.objects.exclude(skills="").exclude(skills__isnull=True)

    for profile in profiles:
        # Convert comma-separated skills to pipe-separated
        if profile.skills:
            skills_list = [
                skill.strip() for skill in profile.skills.split(",") if skill.strip()
            ]
            profile.skills = " | ".join(skills_list)
            profile.save(update_fields=["skills"])


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_rename_current_position_to_most_recent_title"),
    ]

    operations = [
        migrations.RunPython(convert_comma_to_pipe),
    ]
