# Generated by Django 5.1.7 on 2025-03-16 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_move_role_recommendation_from_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolerecommendation",
            name="job_seeker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_recommendations",
                to="job_seekers.jobseekerprofile",
            ),
        ),
    ]
