# Generated by Django 5.1.7 on 2025-03-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_jobseekerprofile_resume_xml"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="about_me",
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="professional_summary",
            field=models.TextField(
                blank=True,
                help_text="Professional summary highlighting experience and qualifications",
                null=True,
            ),
        ),
    ]
