# Generated by Django 5.1.7 on 2025-03-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_alter_rolerecommendation_created_at_talentsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentsheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("INACTIVE", "Inactive"),
                ],
                default="DRAFT",
                help_text="The status of this talent sheet",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rolerecommendation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this recommendation was generated"
            ),
        ),
    ]
