# Generated by Django 5.2 on 2025-04-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0002_jobseekerprofile_candidate_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Phone number", max_length=30, null=True
            ),
        ),
    ]
