# Generated by Django 5.1.7 on 2025-03-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0003_rename_about_me_to_professional_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
    ]
