# Generated by Django 5.2 on 2025-04-30 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0003_alter_jobseekerprofile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedresumepool",
            name="job_opening",
        ),
    ]
