# Generated by Django 5.1.7 on 2025-03-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0003_talentsheet_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="talentsheet",
            name="status",
        ),
        migrations.AddField(
            model_name="talentsheet",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether this talent sheet is published and visible to recruiters",
            ),
        ),
    ]
