# Generated by Django 5.1.7 on 2025-04-18 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0003_remove_rolerecommendation_uploaded_resume_pool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="talentsheet",
            name="personal_tagline",
            field=models.CharField(
                blank=True,
                help_text="AI-generated personal identity tagline",
                max_length=150,
                null=True,
            ),
        ),
    ]
