# Generated by Django 5.1.7 on 2025-03-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0003_update_role_recommendation_related_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolerecommendation",
            options={"ordering": ["role_title"]},
        ),
        migrations.RemoveField(
            model_name="rolerecommendation",
            name="confidence_score",
        ),
    ]
