# Generated by Django 5.2 on 2025-04-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0004_talentsheet_personal_tagline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolerecommendation",
            options={},
        ),
    ]
