# Generated by Django 5.1.7 on 2025-03-15 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0004_jobseekerprofile_education"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="certifications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Phone number", max_length=20, null=True
            ),
        ),
    ]
