# Generated by Django 5.1.7 on 2025-03-15 22:13

import re

from django.db import migrations


def fix_skills_formatting(apps, schema_editor):
    """
    Fix skills that were incorrectly converted in the previous migration.
    Specifically looking for skills that contain parentheses with commas inside them.
    """
    JobSeekerProfile = apps.get_model("job_seekers", "JobSeekerProfile")

    # Regex to find skills with format "Something (A | B)" which should be "Something (A, B)"
    paren_regex = re.compile(r"\(([^)]*)\s\|\s([^)]*)\)")

    # Get all profiles with skills that might have this issue
    profiles = JobSeekerProfile.objects.exclude(skills="").exclude(skills__isnull=True)

    for profile in profiles:
        if profile.skills and " | " in profile.skills:
            # Check for parenthesized content with pipes
            if re.search(paren_regex, profile.skills):
                # Fix parenthesized lists
                fixed_skills = re.sub(paren_regex, r"(\1, \2)", profile.skills)
                profile.skills = fixed_skills
                profile.save(update_fields=["skills"])


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0003_convert_skills_to_pipe_format"),
    ]

    operations = [
        migrations.RunPython(fix_skills_formatting),
    ]
