# Generated by Django 5.1.7 on 2025-03-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0004_remove_confidence_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="personal_tagline",
            field=models.CharField(
                blank=True,
                help_text="AI-generated personal identity tagline",
                max_length=150,
                null=True,
            ),
        ),
    ]
