# Generated by Django 5.2 on 2025-04-20 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0005_alter_rolerecommendation_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeProcessingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the resume processing completed",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        default="success",
                        help_text="Result of the processing job",
                        max_length=20,
                    ),
                ),
                (
                    "job_seeker_profile",
                    models.ForeignKey(
                        help_text="Job seeker profile that was processed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_jobs",
                        to="job_seekers.jobseekerprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the resume processing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_processing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume Processing Job",
                "verbose_name_plural": "Resume Processing Jobs",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.CreateModel(
            name="UsagePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_quota",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Maximum resumes the user can process per rolling month; 0 means unlimited",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User this plan applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_plan",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
