# Generated by Django 5.1.7 on 2025-03-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0005_jobseekerprofile_personal_tagline"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolerecommendation",
            name="is_candidate_interested",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the job seeker has expressed interest in this role",
            ),
        ),
    ]
