# Generated by Django 5.1.7 on 2025-03-15 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0005_fix_skills_formatting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.TextField(
                blank=True, help_text="Pipe-separated list of skills"
            ),
        ),
        migrations.CreateModel(
            name="TaskProgress",
            fields=[
                (
                    "task_id",
                    models.CharField(
                        help_text="Django Q2 task ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        default="resume_processing",
                        help_text="Type of task being processed",
                        max_length=50,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        default="initializing",
                        help_text="Current step being processed",
                        max_length=100,
                    ),
                ),
                (
                    "progress_percent",
                    models.IntegerField(
                        default=0, help_text="Overall progress percentage (0-100)"
                    ),
                ),
                (
                    "steps_completed",
                    models.TextField(
                        blank=True,
                        default="[]",
                        help_text="JSON list of completed steps",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Status message or error details"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
