# Generated by Django 5.1.7 on 2025-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0005_remove_jobseekerprofile_in_talent_pool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="Job seeker's location", max_length=100
            ),
        ),
    ]
