# Generated by Django 5.1.7 on 2025-03-23 04:53

from django.db import migrations


def copy_location_data(apps, schema_editor):
    """
    This migration was intended to copy location data from User model to JobSeekerProfile model.

    However, the User model doesn't have a location field. This is a no-op migration.
    If you need to populate location data, you can do so through the admin interface
    or another data source.
    """
    # No-op - User model doesn't have a location field
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0006_jobseekerprofile_location"),
    ]

    operations = [
        migrations.RunPython(copy_location_data, migrations.RunPython.noop),
    ]
