# Generated by Django 5.1.7 on 2025-03-17 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0006_rolerecommendation_is_candidate_interested"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="in_job_pool",
            field=models.BooleanField(
                default=False,
                help_text="Whether the job seeker is active in the job pool and available for matching",
            ),
        ),
        migrations.AlterField(
            model_name="rolerecommendation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this recommendation was generated"
            ),
        ),
        migrations.AlterField(
            model_name="rolerecommendation",
            name="description",
            field=models.TextField(
                help_text="A concise description of the role, outlining key responsibilities and value proposition"
            ),
        ),
        migrations.AlterField(
            model_name="rolerecommendation",
            name="job_seeker",
            field=models.ForeignKey(
                help_text="The job seeker this role recommendation is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_recommendations",
                to="job_seekers.jobseekerprofile",
            ),
        ),
        migrations.AlterField(
            model_name="rolerecommendation",
            name="role_title",
            field=models.CharField(
                help_text="The title of the recommended role, in title case (e.g., 'Senior Software Engineer')",
                max_length=100,
            ),
        ),
    ]
