# Generated by Django 5.2.1 on 2025-05-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0006_rename_skill_overview_experience_overview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talentsheet",
            name="experience_overview",
            field=models.TextField(
                help_text="Abbreviated overview of the candidate's recent employment experience and demonstrated impact"
            ),
        ),
    ]
