# Generated by Django 5.1.7 on 2025-03-23 04:53

from django.db import migrations


def copy_location_data(apps, schema_editor):
    """Copy location data from User model to JobSeekerProfile model"""
    User = apps.get_model("authentication", "User")
    JobSeekerProfile = apps.get_model("job_seekers", "JobSeekerProfile")

    # Get all job seekers with location
    job_seekers = User.objects.filter(user_type="job_seeker").exclude(location="")

    for user in job_seekers:
        try:
            # Update the job seeker profile with the location from the user
            JobSeekerProfile.objects.filter(user=user).update(location=user.location)
        except Exception:
            # Skip if there's an error
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0006_jobseekerprofile_location"),
    ]

    operations = [
        migrations.RunPython(copy_location_data, migrations.RunPython.noop),
    ]
