# Generated by Django 5.2 on 2025-04-20 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0006_resumeprocessingjob_usageplan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumeprocessingtaskprogress",
            name="user",
        ),
        migrations.RemoveField(
            model_name="usageplan",
            name="user",
        ),
        migrations.DeleteModel(
            name="ResumeProcessingJob",
        ),
        migrations.DeleteModel(
            name="ResumeProcessingTaskProgress",
        ),
        migrations.DeleteModel(
            name="UsagePlan",
        ),
    ]
