# Generated by Django 5.1.7 on 2025-03-16 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0006_alter_jobseekerprofile_skills_taskprogress"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TaskProgress",
            new_name="ResumeProcessingTaskProgress",
        ),
        migrations.AlterModelOptions(
            name="resumeprocessingtaskprogress",
            options={},
        ),
        migrations.AlterField(
            model_name="resumeprocessingtaskprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resume_processing_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
