# Generated by Django 5.1.7 on 2025-03-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0007_jobseekerprofile_in_job_pool_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobseekerprofile",
            name="in_job_pool",
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="in_talent_pool",
            field=models.BooleanField(
                default=False,
                help_text="Whether the job seeker is active in the talent pool and available for matching",
            ),
        ),
    ]
