# Generated by Django 5.2.1 on 2025-05-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0008_convert_skills_delimiter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="skills",
            field=models.TextField(
                blank=True, help_text="Line-separated list of skills"
            ),
        ),
    ]
