# Generated by Django 5.2.1 on 2025-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_seekers", "0010_convert_talentsheet_skills_delimiter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="talentsheet",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Line-separated list of skills copied from JobSeekerProfile.skills for matching purposes",
            ),
        ),
    ]
