# Generated by Django 5.1.6 on 2025-03-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Job Seeker"),
                    ("recruiter", "Recruiter"),
                    ("admin", "Administrator"),
                ],
                default="job_seeker",
                max_length=20,
                verbose_name="user type",
            ),
        ),
    ]
