# Generated by Django 5.1.7 on 2025-03-14 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
    ]
