# Generated by Django 5.1.7 on 2025-03-15 03:30

from django.db import migrations, models


def combine_names(apps, schema_editor):
    """
    Combine first_name and last_name into a single name field.

    This preserves existing user name data during the migration.
    """
    User = apps.get_model("authentication", "User")
    for user in User.objects.all():
        full_name = f"{user.first_name} {user.last_name}".strip()
        user.name = full_name if full_name else "New User"
        user.save(update_fields=["name"])


def reverse_name_combination(apps, schema_editor):
    """
    Split name back into first_name and last_name (reverse migration).

    Best effort to restore the original data.
    """
    User = apps.get_model("authentication", "User")
    for user in User.objects.all():
        name_parts = user.name.split(" ", 1)
        user.first_name = name_parts[0] if len(name_parts) > 0 else ""
        user.last_name = name_parts[1] if len(name_parts) > 1 else ""
        user.save(update_fields=["first_name", "last_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_bio_field"),
    ]

    operations = [
        # Add name field first
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="New User", max_length=255, verbose_name="name"
            ),
        ),
        # Then run the data migration to combine names
        migrations.RunPython(combine_names, reverse_name_combination),
        # Finally remove the old fields
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
