# Generated by Django 5.2.1 on 2025-05-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_backfill_user_type_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_us_certified",
            field=models.BooleanField(
                default=False,
                help_text="Indicates that the user has confirmed they are physically located in the United States and will use the platform solely for US-based hiring activities.",
                verbose_name="US certified",
            ),
        ),
    ]
