# Generated by Django 5.2.5 on 2025-10-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("job_seeker", "Job Seeker"),
                    ("recruiter", "Recruiter"),
                    ("admin", "Administrator"),
                ],
                default="recruiter",
                max_length=20,
                verbose_name="user type",
            ),
        ),
    ]
