# Generated by Django 5.2.7 on 2025-11-03 05:57

import apps.authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                default="New User",
                max_length=255,
                validators=[apps.authentication.validators.validate_recruiter_name],
                verbose_name="name",
            ),
        ),
    ]
